c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:          # [aarch64]
  - sbsa                   # [aarch64]
cross_target_platform:
  - linux-64       # [linux]
  - linux-aarch64  # [linux]
  - win-64         # [win]
