c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
arm_variant_target:
  - None
  - sbsa                   # [linux]
  - tegra                  # [linux]
cross_target_platform:
  - None           # [not (linux or win)]
  - linux-64       # [linux]
  - linux-aarch64  # [linux]
  - linux-aarch64  # [linux]
  - win-64         # [win]
# https://docs.nvidia.com/cuda/archive/12.9.1/cuda-compiler-driver-nvcc/#virtual-architecture-feature-list
# https://docs.nvidia.com/cuda/archive/12.9.1/cuda-compiler-driver-nvcc/#gpu-feature-list
DEFAULT_CUDAARCHS:
  - "50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90a-real;100f-real;103f-real;120a-real;121f-real;121-virtual"
  - "50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90a-real;100f-real;103f-real;120a-real;121f-real;121-virtual"  # [linux]
  - "87-real;101f-real;101-virtual"  # [linux]

zip_keys:
  - arm_variant_target
  - cross_target_platform
  - DEFAULT_CUDAARCHS
