c_compiler_version:        # [linux]
  - 14                     # [linux]
cxx_compiler_version:      # [linux]
  - 14                     # [linux]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
arm_variant_target:
  - None
  - sbsa                   # [linux]
cross_target_platform:
  - None           # [not (linux or win)]
  - linux-64       # [linux]
  - linux-aarch64  # [linux]
  - win-64         # [win]
DEFAULT_CUDAARCHS:
  - "75-real;80-real;86-real;89-real;90a-real;100f-real;103f-real;120a-real;121f-real;121-virtual"
  # aarch64 has more targets than x86 because Tegra devices are sbsa aarch64 only
  - "75-real;80-real;86-real;87-real;89-real;90a-real;100f-real;103f-real;110-real;120a-real;121f-real;121-virtual"  # [linux]
DEFAULT_NVCC_GENCODE:
  - "-gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90a,code=sm_90a -gencode arch=compute_100f,code=sm_100f -gencode arch=compute_103f,code=sm_103f -gencode arch=compute_120a,code=sm_120a -gencode arch=compute_121f,code=sm_121f -gencode arch=compute_121,code=compute_121"
  # aarch64 has more targets than x86 because Tegra devices are sbsa aarch64 only
  - "-gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 -gencode arch=compute_87,code=sm_87 -gencode arch=compute_89,code=sm_89 -gencode arch=compute_90a,code=sm_90a -gencode arch=compute_100f,code=sm_100f -gencode arch=compute_103f,code=sm_103f -gencode arch=compute_110,code=sm_110 -gencode arch=compute_120a,code=sm_120a -gencode arch=compute_121f,code=sm_121f -gencode arch=compute_121,code=compute_121"  # [linux]

zip_keys:
  - arm_variant_target
  - cross_target_platform
  - DEFAULT_CUDAARCHS
  - DEFAULT_NVCC_GENCODE
